---
- hosts: localhost

  vars_files:
    - vars/common.yaml

  tasks:
    - name: Set up packages
      ansible.builtin.include_tasks: tasks/packages.yaml

    - name: Set up auto updates
      ansible.builtin.include_tasks: tasks/auto-updates.yaml

    - name: Configure firewall
      ansible.builtin.include_tasks: tasks/firewall.yaml

    - name: Set up dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yaml

    - name: Allow ext automount
      ansible.builtin.include_tasks: tasks/automount.yaml

    - name: Configure audio
      ansible.builtin.include_tasks: tasks/audio.yaml

    - name: Set up swapfile for hibernation
      ansible.builtin.include_tasks: tasks/hibernation.yaml
