---
- hosts: localhost

  vars_files:
    - vars/common.yaml

  tasks:
    - name: Set up packages
      ansible.builtin.include_tasks: tasks/packages.yaml

    - name: Set up dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yaml

