---
- name: Install dnf-automatic
  become: true
  ansible.builtin.dnf:
    name:
      - dnf5-plugin-automatic

- name: Configure dnf-automatic
  become: true
  template:
    src: automatic.conf
    dest: /etc/dnf/automatic.conf

- name: Enable dnf-automatic
  become: true
  ansible.builtin.systemd_service:
    name: dnf5-automatic.timer
    enabled: true
    state: started
