---
- name: Install chezmoi
  ansible.builtin.dnf:
    name: "https://github.com/twpayne/chezmoi/releases/download/v{{chezmoi.version}}/chezmoi-{{chezmoi.version}}-x86_64.rpm"
    state: present
    disable_gpg_check: yes
  become: true
